eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
zuul:
  sensitive-headers: Cookie,Set-Cookie
  debug:
    request: true
#  prefix: /api
  routes:
    user-management-service:
     path: /**/v1/**/
     url: http://localhost:8084
     stripPrefix: false
    fare-calculation-service:
     path: /**/v2/**/
     url: http://localhost:8085
     stripPrefix: false
     
    
    
   
spring:
  application:
    name: zuul-api-gateway
server:
  port: 8989
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
